// examples/next-openai/app/completion/page.tsx
'use client';

import { useCompletion } from '@ai-toolkit/react';

export default function Page() {
  const {
    completion,
    input,
    handleInputChange,
    handleSubmit,
    error,
    data,
    isLoading,
    stop,
  } = useCompletion();

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      <h4 className="pb-4 text-xl font-bold text-gray-900 md:text-xl">
        useCompletion Example
      </h4>
      {data && (
        <pre className="p-4 text-sm bg-gray-100">
          {JSON.stringify(data, null, 2)}
        </pre>
      )}
      {error && (
        <div className="fixed top-0 left-0 w-full p-4 text-center text-white bg-red-500">
          {error.message}
        </div>
      )}
      {isLoading && (
        <div className="mt-4 text-gray-500">
          <div>Loading...</div>
          <button
            type="button"
            className="px-4 py-2 mt-4 text-blue-500 border border-blue-500 rounded-md"
            onClick={stop}
          >
            Stop
          </button>
        </div>
      )}
      {completion}
      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
          disabled={isLoading}
        />
      </form>
    </div>
  );
}

// examples/solidstart-openai/src/routes/completion/index.tsx
import { useCompletion } from '@ai-toolkit/solid';
import { JSX } from 'solid-js';

export default function Chat() {
  const { completion, input, setInput, handleSubmit, error, data } =
    useCompletion();

  const handleInputChange: JSX.ChangeEventHandlerUnion<
    HTMLInputElement,
    Event
  > = e => {
    setInput(e.target.value);
  };

  return (
    <div class="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {data() && (
        <pre class="p-4 text-sm bg-gray-100">
          {JSON.stringify(data(), null, 2)}
        </pre>
      )}

      {error() && (
        <div class="fixed top-0 left-0 w-full p-4 text-center bg-red-500 text-white">
          {error()?.message}
        </div>
      )}

      {completion()}

      <form onSubmit={handleSubmit}>
        <input
          class="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input()}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}
